"""Generate the Inno Setup model choices from installer/models.toml.

Inno Setup can't read TOML, so CI runs this before ISCC (release.yml). It
writes two include files next to loka.iss:

- models.components.iss: the [Types] and [Components] sections. One "model"
  parent checkbox, with one child per model flagged `exclusive`, so the user
  picks at most one model (radio buttons), or none by unticking the parent.
  The first model in models.toml is the default.
- models.code.iss: a Pascal function `SelectedModel(var Id, Repo: String):
  Boolean` used by WriteInstallManifest to record the chosen model in
  install-selection.toml.

Usage: python installer/gen_models.py [models.toml] [output dir]
"""

from __future__ import annotations

import re
import sys
import tomllib
from pathlib import Path

REQUIRED = ("id", "display_name", "hf_repo", "approx_size")


def load_models(toml_text: str) -> list[dict]:
    """Parse and validate the [[model]] list."""
    models = tomllib.loads(toml_text).get("model", [])
    if not models:
        raise ValueError("models.toml has no [[model]] entries")
    seen = set()
    for m in models:
        missing = [k for k in REQUIRED if not m.get(k)]
        if missing:
            raise ValueError(f"model {m.get('id', '?')!r} is missing {missing}")
        if m["id"] in seen:
            raise ValueError(f"duplicate model id {m['id']!r}")
        seen.add(m["id"])
        for k in REQUIRED:
            if any(c in m[k] for c in '"\r\n'):
                raise ValueError(f"model {m['id']!r}: {k} must not contain quotes or newlines")
    return models


def component_name(model_id: str) -> str:
    """Inno component names: letters, digits and underscores only."""
    return "model\\" + re.sub(r"[^A-Za-z0-9_]", "_", model_id)


def render_components(models: list[dict]) -> str:
    lines = [
        "; Generated by installer/gen_models.py from models.toml. Do not edit.",
        "[Types]",
        'Name: "engine_only"; Description: "Database only (just Loka, no inference model)"',
        'Name: "engine_model"; Description: "Database + an inference model (downloaded on first launch)"; Flags: iscustom',
        "",
        "[Components]",
        'Name: "engine"; Description: "Loka engine (loka.exe, required)"; Types: engine_only engine_model; Flags: fixed',
        'Name: "model"; Description: "Inference model (pick one; downloaded on first launch from Hugging Face)"; Types: engine_model',
    ]
    for i, m in enumerate(models):
        types = "engine_model" if i == 0 else ""  # the first model is the default choice
        lines.append(
            f'Name: "{component_name(m["id"])}"; '
            f'Description: "{m["display_name"]} ({m["approx_size"]})"; '
            f'Types: {types}; Flags: exclusive'.replace("Types: ; ", "")
        )
    return "\n".join(lines) + "\n"


def render_code(models: list[dict]) -> str:
    lines = [
        "{ Generated by installer/gen_models.py from models.toml. Do not edit. }",
        "function SelectedModel(var Id, Repo: String): Boolean;",
        "begin",
        "  Result := False;",
        "  Id := '';",
        "  Repo := '';",
    ]
    for m in models:
        lines += [
            f"  if IsComponentSelected('{component_name(m['id'])}') then",
            "  begin",
            f"    Id := '{m['id']}';",
            f"    Repo := '{m['hf_repo']}';",
            "    Result := True;",
            "  end;",
        ]
    lines.append("end;")
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    here = Path(__file__).resolve().parent
    toml_path = Path(argv[1]) if len(argv) > 1 else here / "models.toml"
    out_dir = Path(argv[2]) if len(argv) > 2 else here
    models = load_models(toml_path.read_text(encoding="utf-8"))
    (out_dir / "models.components.iss").write_text(render_components(models), encoding="utf-8")
    (out_dir / "models.code.iss").write_text(render_code(models), encoding="utf-8")
    print(f"{len(models)} model(s): {', '.join(m['id'] for m in models)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
